In [12]:
# import pytorch 
import torch

## Tensors 

In [15]:
# creating tensors

# Numbers 

t1 = torch.tensor(4.)
print(t1)
print(f"The type of {t1} is {t1.dtype} with shape {t1.shape}")
# vectors 

t2 = torch.tensor([1.,2,3,4])
print(t2)
print(f"The type of {t2} is {t2.dtype} with shape {t2.shape}")
# matrix
t3 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6.]
])
print(t3)
print(f"The type of {t3} is {t3.dtype} with shape {t3.shape}")
# 3 - dimensional array

t4 = torch.tensor([[[1,2,3],
                   [4,5,6]],
                   
                   [[7,8,9],
                    [10,11,12.]]])

print(t3)
print(f"The type of {t4} is {t4.dtype} with shape {t4.shape}")

tensor(4.)
The type of 4.0 is torch.float32 with shape torch.Size([])
tensor([1., 2., 3., 4.])
The type of tensor([1., 2., 3., 4.]) is torch.float32 with shape torch.Size([4])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
The type of tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) is torch.float32 with shape torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
The type of tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]]) is torch.float32 with shape torch.Size([2, 2, 3])


## Tensor operations and gradients

In [3]:
# create tensors 

a = torch.tensor(3.)
b = torch.tensor(4., requires_grad= True)
c 

In [4]:
# arithmetic operation



In [5]:
# computing derivatives



In [ ]:
# display gradients

