## Gradient Descent and Linear Regression in Pytorch

In [1]:
# import the required libraries

import numpy as np
import torch
import matplotlib.pyplot as plt

In [2]:
# create the training set. a numpy array of [temp, rainfall, humidity]
# 

inputs = np.array([[22, 65, 34],
                   [91,38, 64],
                   [87, 45, 55,],
                   [102, 43, 37],
                   [69,96, 70]], dtype = 'float32')



In [3]:
# creating the target array
targets = np.array([[56, 70],
                    [81,101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype = 'float32' )

In [4]:
# convert the arrays to pytorch tensors

input_tensor = torch.from_numpy(inputs)
targets_tensor = torch.from_numpy(targets)

In [5]:
# creating the weights and bias from a normal distribution

# weights and bias 

w = torch.randn(2, 3, requires_grad= True)
b = torch.randn(2, requires_grad= True)



In [6]:
# getting predictions 

input_tensor @ w.t() + b

tensor([[ 90.2563, -28.9483],
        [ 39.5986,   7.5583],
        [ 57.7656,  -9.8045],
        [ 73.3165, -38.7970],
        [127.9197, -32.7657]], grad_fn=<AddBackward0>)

In [7]:
# create a prediction model function

def model(x):
    return x @ w.t() + b

In [8]:
# generate prediction

preds = model(x = input_tensor)
preds

tensor([[ 90.2563, -28.9483],
        [ 39.5986,   7.5583],
        [ 57.7656,  -9.8045],
        [ 73.3165, -38.7970],
        [127.9197, -32.7657]], grad_fn=<AddBackward0>)

In [9]:
#compare with target

print(targets_tensor)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [10]:
# computing Loss Function


# create a mean square error function

def mse(y_pred, y_true):
    diff = y_pred - y_true
    return torch.sum(diff * diff)/diff.numel()

In [11]:
# calling the mse function

loss = mse(y_pred=preds, y_true= targets_tensor)

print(loss)

tensor(7758.4858, grad_fn=<DivBackward0>)


In [12]:
# Setting up gradient descent

loss.backward()

learning_rate = 1e-5

with torch.no_grad():
    w -= w.grad * learning_rate
    b -= b.grad * learning_rate 

In [13]:
preds = model(input_tensor)
loss = mse(y_pred=preds, y_true= targets_tensor)
print(loss)

tensor(6319.2578, grad_fn=<DivBackward0>)


### gradient descent steps
1. make predictions
2. calculate the loss
3. calculate the gradient of the loss w.r.t weight and bias 
4. adjust the gradients by either subtracting or adding learning rate
5. reset the gradient to zero

In [14]:
for i in range(100):
    preds = model(input_tensor) # make prediction
    loss = mse(y_pred= preds, y_true= targets_tensor) # calculate the loss
    loss.backward() # getting the gradient wrt to weight and bias 
    with torch.no_grad():
        # adjust the weight and bias slightly by adding or subtracting
        # learning rate
        w -= w * learning_rate
        b -= b * learning_rate
        # reset the gradients to zero
        w.grad.zero_()
        b.grad.zero_()
        

In [15]:
# getting the current state of the model

preds = model(input_tensor)
loss = mse(y_pred=preds, y_true= targets_tensor)
print(loss)

tensor(6317.6108, grad_fn=<DivBackward0>)


To achieve better result you will have to experiment with different
hyperparameters (learning rate, batch size etc....)