## Gradient Descent and Linear Regression in Pytorch

In [1]:
# import the required libraries

import numpy as np
import torch
import matplotlib.pyplot as plt

In [5]:
# create the training set. a numpy array of [temp, rainfall, humidity]
# 

inputs = np.array([[22, 65, 34],
                   [91,38, 64],
                   [87, 45, 55,],
                   [102, 43, 37],
                   [69,96, 70]], dtype = 'float32')



In [9]:
# creating the target array
targets = np.array([[56, 70],
                    [81,101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype = 'float32' )

In [10]:
# convert the arrays to pytorch tensors

input_tensor = torch.from_numpy(inputs)
targets_tensor = torch.from_numpy(targets)

In [11]:
# creating the weights and bias from a normal distribution

# weights and bias 

w = torch.randn(2, 3, requires_grad= True)
b = torch.randn(2, requires_grad= True)



In [13]:
# getting predictions 

input_tensor @ w.t() + b

tensor([[ 61.6717, -21.8846],
        [ 85.5525,  85.7914],
        [ 90.1875,  67.5508],
        [103.9166,  65.9146],
        [114.7250,  11.9552]], grad_fn=<AddBackward0>)

In [16]:
# create a prediction model function

def model(x):
    return x @ w.t() + b

In [17]:
# generate prediction

preds = model(x = input_tensor)
preds

tensor([[ 61.6717, -21.8846],
        [ 85.5525,  85.7914],
        [ 90.1875,  67.5508],
        [103.9166,  65.9146],
        [114.7250,  11.9552]], grad_fn=<AddBackward0>)

In [18]:
#compare with target

print(targets_tensor)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [19]:
# computing Loss Function


# create a mean square error function

def mse(y_pred, y_true):
    diff = y_pred - y_true
    return torch.sum(diff * diff)/diff.numel()

In [ ]:
# calling th