In [6]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [14]:
# creating the input array

inputs = np.random.randint(30, 102, size=(15,3))

# creating the target array

target = np.random.randint(10, 45, size=(15,2)) * 30 + 10

In [16]:
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

In [17]:
# create a dataloader 

from torch.utils.data import  TensorDataset

In [18]:
train_ds = TensorDataset(inputs, target)

train_ds[0:3]

(tensor([[62, 58, 48],
         [74, 58, 64],
         [83, 84, 65]], dtype=torch.int32),
 tensor([[1180, 1000],
         [ 490,  820],
         [1000,  820]], dtype=torch.int32))

In [19]:
# create the dataloader for splitting the data into
# batches


from torch.utils.data import  DataLoader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [20]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 96,  82,  67],
        [ 83,  84,  65],
        [ 94,  41, 100],
        [ 99,  86,  58],
        [ 70,  63,  91]], dtype=torch.int32)
tensor([[1030, 1150],
        [1000,  820],
        [ 760,  460],
        [ 520,  400],
        [ 790,  400]], dtype=torch.int32)
